FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 5000

# Usar directamente CMD con un comando de shell en lugar de un script
CMD sh -c "echo 'Esperando a que MongoDB esté disponible...' && sleep 15 && echo 'Ejecutando seed...' && npm run seed && echo 'Iniciando servidor...' && npm run dev"