import Ejercicio from '../../models/training/ejercicio';
import mongoose from 'mongoose';

export async function seedEjercicios() {
  try {
    console.log('Iniciando seed de ejercicios...');

    // Verificar conexión
    if (mongoose.connection.readyState !== 1) {
      console.log('Reconectando a MongoDB...');
      const mongoUri = process.env.MONGO_URI || 'mongodb://localhost:27017/nutroos';
      await mongoose.connect(mongoUri);
    }

    // Limpiar ejercicios existentes
    await Ejercicio.deleteMany({});
    console.log('Ejercicios existentes eliminados.');

    const ejercicios = [
      // === PECHO ===
      {
        nombre: 'Press de banca',
        slug: 'press-de-banca',
        descripcion: 'Ejercicio básico para desarrollo del pecho con barra',
        grupoMuscular: 'Pecho',
        equipamiento: 'Barra',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Fuerza',
        instrucciones: 'Acuéstate en banco, agarra la barra con las manos separadas al ancho de los hombros, baja controladamente y empuja hacia arriba',
        videoDemostrativo: 'https://wger.de/media/exercise-video/73/2bdb390c-312c-4497-a722-5eed2c823e5a.MOV',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Flexiones',
        slug: 'flexiones',
        descripcion: 'Ejercicio de peso corporal para pecho',
        grupoMuscular: 'Pecho',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Fuerza',
        instrucciones: 'Posición de plancha, manos separadas al ancho de los hombros, baja el pecho al suelo y empuja hacia arriba',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Press inclinado con mancuernas',
        slug: 'press-inclinado-mancuernas',
        descripcion: 'Press de pecho en banco inclinado con mancuernas',
        grupoMuscular: 'Pecho',
        equipamiento: 'Mancuernas',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Fuerza',
        instrucciones: 'Acuéstate en banco inclinado 30-45°, agarra mancuernas y presiona hacia arriba',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Aperturas con mancuernas',
        slug: 'aperturas-mancuernas',
        descripcion: 'Ejercicio de aislamiento para pecho con mancuernas',
        grupoMuscular: 'Pecho',
        equipamiento: 'Mancuernas',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Fuerza',
        instrucciones: 'Acuéstate en banco, extiende brazos con mancuernas y abre en arco hasta sentir estiramiento',
        arquetipo: true,
        publico: true,
        activo: true
      },

      // === ESPALDA ===
      {
        nombre: 'Dominadas',
        slug: 'dominadas',
        descripcion: 'Ejercicio de peso corporal para espalda',
        grupoMuscular: 'Espalda',
        equipamiento: 'Barra de dominadas',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Fuerza',
        instrucciones: 'Cuelga de la barra, manos separadas al ancho de los hombros, tira hacia arriba hasta que el mentón pase la barra',
        videoDemostrativo: 'https://wger.de/media/exercise-video/475/83067ffe-ccb9-4e22-8507-5131b211ce74.MOV',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Remo con barra',
        slug: 'remo-barra',
        descripcion: 'Ejercicio de remo con barra para espalda',
        grupoMuscular: 'Espalda',
        equipamiento: 'Barra',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Fuerza',
        instrucciones: 'Inclinado 45°, agarra la barra y tira hacia el abdomen, apretando los omóplatos',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Peso muerto',
        slug: 'peso-muerto',
        descripcion: 'Ejercicio fundamental para espalda y cadena posterior',
        grupoMuscular: 'Espalda',
        equipamiento: 'Barra',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Fuerza',
        instrucciones: 'Pies separados al ancho de los hombros, agarra la barra y levántala manteniendo la espalda recta',
        arquetipo: true,
        publico: true,
        activo: true
      },

      // === HOMBROS ===
      {
        nombre: 'Press militar',
        slug: 'press-militar',
        descripcion: 'Press de hombros con barra de pie',
        grupoMuscular: 'Hombros',
        equipamiento: 'Barra',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Fuerza',
        instrucciones: 'De pie, agarra la barra al ancho de los hombros y presiona hacia arriba',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Elevaciones laterales',
        slug: 'elevaciones-laterales',
        descripcion: 'Ejercicio de aislamiento para deltoides laterales',
        grupoMuscular: 'Hombros',
        equipamiento: 'Mancuernas',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Fuerza',
        instrucciones: 'De pie, eleva mancuernas lateralmente hasta la altura de los hombros',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Elevaciones frontales',
        slug: 'elevaciones-frontales',
        descripcion: 'Ejercicio de aislamiento para deltoides frontales',
        grupoMuscular: 'Hombros',
        equipamiento: 'Mancuernas',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Fuerza',
        instrucciones: 'De pie, eleva mancuernas frontalmente hasta la altura de los hombros',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Tirón facial',
        slug: 'tiron-facial',
        descripcion: 'Ejercicio para deltoides posteriores y trapecio',
        grupoMuscular: 'Hombros',
        equipamiento: 'Cable',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Fuerza',
        instrucciones: 'Con cable, tira hacia la cara separando las manos',
        videoDemostrativo: 'https://wger.de/media/exercise-video/222/245a824b-cd39-45f2-b251-2c0b7efead0d.MOV',
        arquetipo: true,
        publico: true,
        activo: true
      },

      // === PIERNAS ===
      {
        nombre: 'Sentadilla',
        slug: 'sentadilla',
        descripcion: 'Ejercicio fundamental para piernas',
        grupoMuscular: 'Piernas',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Fuerza',
        instrucciones: 'Pies separados al ancho de los hombros, baja como si te sentaras en una silla',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Sentadilla con barra',
        slug: 'sentadilla-barra',
        descripcion: 'Sentadilla con barra en la espalda',
        grupoMuscular: 'Piernas',
        equipamiento: 'Barra',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Fuerza',
        instrucciones: 'Barra en la espalda, baja hasta que los muslos estén paralelos al suelo',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Zancadas',
        slug: 'zancadas',
        descripcion: 'Ejercicio unilateral para piernas',
        grupoMuscular: 'Piernas',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Fuerza',
        instrucciones: 'Da un paso largo hacia adelante y baja la rodilla trasera al suelo',
        videoDemostrativo: 'https://wger.de/media/exercise-video/802/85d1d7f8-c3c5-47e8-9b26-56896919e6e7.MOV',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Peso muerto rumano',
        slug: 'peso-muerto-rumano',
        descripcion: 'Variación del peso muerto enfocada en isquiotibiales',
        grupoMuscular: 'Piernas',
        equipamiento: 'Barra',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Fuerza',
        instrucciones: 'Barra en las manos, mantén las piernas casi rectas y baja la barra hacia los pies',
        videoDemostrativo: 'https://wger.de/media/exercise-video/507/307e7276-a14d-4ea0-b579-f5b0dbc6f5af.MOV',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Sentadillas búlgaras',
        slug: 'sentadillas-bulgaras',
        descripcion: 'Sentadilla búlgara con pie trasero elevado',
        grupoMuscular: 'Piernas',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Fuerza',
        instrucciones: 'Pie trasero en banco, baja la rodilla delantera hacia el suelo',
        arquetipo: true,
        publico: true,
        activo: true
      },

      // === BRAZOS ===
      {
        nombre: 'Curl de bíceps',
        slug: 'curl-biceps',
        descripcion: 'Ejercicio de aislamiento para bíceps',
        grupoMuscular: 'Brazos',
        equipamiento: 'Mancuernas',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Fuerza',
        instrucciones: 'De pie, flexiona los brazos llevando las mancuernas hacia los hombros',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Tríceps en banco',
        slug: 'triceps-banco',
        descripcion: 'Fondos en banco para tríceps',
        grupoMuscular: 'Brazos',
        equipamiento: 'Banco',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Fuerza',
        instrucciones: 'Apoya las manos en el banco, baja el cuerpo flexionando los codos',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Curl martillo',
        slug: 'curl-martillo',
        descripcion: 'Curl de bíceps con agarre neutro',
        grupoMuscular: 'Brazos',
        equipamiento: 'Mancuernas',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Fuerza',
        instrucciones: 'Agarre neutro, flexiona los brazos manteniendo las muñecas rectas',
        videoDemostrativo: 'https://wger.de/media/exercise-video/272/df069052-2173-4f24-855f-a0eebe729f24.MOV',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Extensiones de tríceps',
        slug: 'extensiones-triceps',
        descripcion: 'Extensiones de tríceps con mancuerna',
        grupoMuscular: 'Brazos',
        equipamiento: 'Mancuernas',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Fuerza',
        instrucciones: 'Mancuerna sobre la cabeza, extiende los brazos hacia arriba',
        arquetipo: true,
        publico: true,
        activo: true
      },

      // === CORE ===
      {
        nombre: 'Plancha',
        slug: 'plancha',
        descripcion: 'Ejercicio isométrico para core',
        grupoMuscular: 'Core',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Fuerza',
        instrucciones: 'Posición de flexión, mantén el cuerpo recto y rígido',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Crunches',
        slug: 'crunches',
        descripcion: 'Abdominales básicos',
        grupoMuscular: 'Core',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Fuerza',
        instrucciones: 'Acostado, flexiona el tronco llevando los hombros hacia las rodillas',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Escaladores de montaña',
        slug: 'mountain-climbers',
        descripcion: 'Ejercicio dinámico para core y cardio',
        grupoMuscular: 'Core',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Cardio',
        instrucciones: 'Posición de plancha, alterna llevando las rodillas al pecho',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Giros rusos',
        slug: 'russian-twists',
        descripcion: 'Rotaciones de tronco para core',
        grupoMuscular: 'Core',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Fuerza',
        instrucciones: 'Sentado, inclínate hacia atrás y rota el tronco de lado a lado',
        arquetipo: true,
        publico: true,
        activo: true
      },

      // === CARDIO/HIIT ===
      {
        nombre: 'Burpees',
        slug: 'burpees',
        descripcion: 'Ejercicio completo de cardio y fuerza',
        grupoMuscular: 'Piernas',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Cardio',
        instrucciones: 'Flexión, salto a sentadilla, salto vertical con brazos arriba',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Saltos de tijera',
        slug: 'jumping-jacks',
        descripcion: 'Ejercicio de cardio básico',
        grupoMuscular: 'Piernas',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Cardio',
        instrucciones: 'Salta separando piernas y brazos, luego vuelve a juntarlos',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Rodillas altas',
        slug: 'high-knees',
        descripcion: 'Carrera en el lugar elevando rodillas',
        grupoMuscular: 'Piernas',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Cardio',
        instrucciones: 'Corre en el lugar elevando las rodillas al pecho',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Sentadillas con salto',
        slug: 'jump-squats',
        descripcion: 'Sentadillas con salto',
        grupoMuscular: 'Piernas',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Cardio',
        instrucciones: 'Haz una sentadilla y salta explosivamente hacia arriba',
        arquetipo: true,
        publico: true,
        activo: true
      },

      // === FLEXIBILIDAD/MOVILIDAD ===
      {
        nombre: 'Estiramiento de isquiotibiales',
        slug: 'estiramiento-isquiotibiales',
        descripcion: 'Estiramiento estático para isquiotibiales',
        grupoMuscular: 'Piernas',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Flexibilidad',
        instrucciones: 'Sentado, extiende una pierna y estírate hacia el pie',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Estiramiento de pecho',
        slug: 'estiramiento-pecho',
        descripcion: 'Estiramiento para músculos del pecho',
        grupoMuscular: 'Pecho',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Flexibilidad',
        instrucciones: 'Coloca el brazo en la pared y gira el cuerpo para estirar el pecho',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Estiramiento de espalda',
        slug: 'estiramiento-espalda',
        descripcion: 'Estiramiento para músculos de la espalda',
        grupoMuscular: 'Espalda',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Flexibilidad',
        instrucciones: 'Sentado, cruza una pierna y gira el tronco hacia el lado opuesto',
        arquetipo: true,
        publico: true,
        activo: true
      },

      // === FUNCIONALES ===
      {
        nombre: 'Balanceos con kettlebell',
        slug: 'kettlebell-swings',
        descripcion: 'Balanceo con kettlebell para cadera y core',
        grupoMuscular: 'Piernas',
        equipamiento: 'Kettlebell',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Fuerza',
        instrucciones: 'Con kettlebell, balancea desde entre las piernas hasta la altura del pecho',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Levantamientos turcos',
        slug: 'turkish-get-ups',
        descripcion: 'Levantamiento turco con kettlebell',
        grupoMuscular: 'Core',
        equipamiento: 'Kettlebell',
        nivelDificultad: 'Avanzado',
        tipoEjercicio: 'Fuerza',
        instrucciones: 'Acostado, levanta la kettlebell y ponte de pie manteniéndola arriba',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Caminata de granjero',
        slug: 'farmer-walks',
        descripcion: 'Caminata con peso para fuerza funcional',
        grupoMuscular: 'Core',
        equipamiento: 'Mancuernas',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Fuerza',
        instrucciones: 'Camina sosteniendo mancuernas pesadas a los lados',
        arquetipo: true,
        publico: true,
        activo: true
      },

      // === RESISTENCIA ===
      {
        nombre: 'Push-ups isométricos',
        slug: 'push-ups-isometricos',
        descripcion: 'Flexiones manteniendo la posición',
        grupoMuscular: 'Pecho',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Fuerza',
        instrucciones: 'Mantén la posición de flexión durante el tiempo especificado',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Sentadilla en pared',
        slug: 'wall-sits',
        descripcion: 'Sentadilla isométrica contra la pared',
        grupoMuscular: 'Piernas',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Fuerza',
        instrucciones: 'Apoya la espalda en la pared y mantén la posición de sentadilla',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Plancha a flexión',
        slug: 'plank-to-push-up',
        descripcion: 'Transición de plancha a flexión',
        grupoMuscular: 'Core',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Fuerza',
        instrucciones: 'Desde plancha, alterna apoyando un brazo y luego el otro',
        arquetipo: true,
        publico: true,
        activo: true
      },

      // === EQUILIBRIO/ESTABILIDAD ===
      {
        nombre: 'Peso muerto a una pierna',
        slug: 'single-leg-deadlifts',
        descripcion: 'Peso muerto a una pierna para equilibrio',
        grupoMuscular: 'Piernas',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Fuerza',
        instrucciones: 'De pie, levanta una pierna y baja el tronco manteniendo el equilibrio',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Sentadillas pistol',
        slug: 'pistol-squats',
        descripcion: 'Sentadilla a una pierna',
        grupoMuscular: 'Piernas',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Avanzado',
        tipoEjercicio: 'Fuerza',
        instrucciones: 'De pie, extiende una pierna y baja en sentadilla con la otra',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Sentadillas en L',
        slug: 'l-sits',
        descripcion: 'Sentadilla en L para core y brazos',
        grupoMuscular: 'Core',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Avanzado',
        tipoEjercicio: 'Fuerza',
        instrucciones: 'Sentado, levanta las piernas y mantén la posición en L',
        arquetipo: true,
        publico: true,
        activo: true
      },

      // === CALENTAMIENTO ===
      {
        nombre: 'Círculos de brazos',
        slug: 'arm-circles',
        descripcion: 'Círculos con los brazos para calentamiento',
        grupoMuscular: 'Hombros',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Flexibilidad',
        instrucciones: 'Extiende los brazos y haz círculos hacia adelante y atrás',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Balanceos de piernas',
        slug: 'leg-swings',
        descripcion: 'Balanceos de piernas para calentamiento',
        grupoMuscular: 'Piernas',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Flexibilidad',
        instrucciones: 'De pie, balancea una pierna hacia adelante y atrás',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Círculos de cadera',
        slug: 'hip-circles',
        descripcion: 'Círculos de cadera para calentamiento',
        grupoMuscular: 'Piernas',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Flexibilidad',
        instrucciones: 'Manos en la cintura, haz círculos con la cadera',
        arquetipo: true,
        publico: true,
        activo: true
      },
      // === EJERCICIOS DE ESTABILIDAD ===
      {
        nombre: 'Plancha lateral',
        slug: 'plancha-lateral',
        descripcion: 'Plancha lateral para estabilidad del core',
        grupoMuscular: 'Core',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Estabilidad',
        instrucciones: 'Apóyate en un antebrazo lateral, mantén el cuerpo recto y contrae el core',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Perro pájaro',
        slug: 'bird-dog',
        descripcion: 'Ejercicio de estabilidad en cuadrupedia',
        grupoMuscular: 'Core',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Estabilidad',
        instrucciones: 'En cuadrupedia, extiende brazo y pierna opuestos manteniendo el equilibrio',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Bicho muerto',
        slug: 'dead-bug',
        descripcion: 'Ejercicio de estabilidad acostado',
        grupoMuscular: 'Core',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Estabilidad',
        instrucciones: 'Acostado boca arriba, brazos y piernas en 90°, baja alternativamente brazo y pierna opuestos',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Press Pallof',
        slug: 'pallof-press',
        descripcion: 'Ejercicio anti-rotación con banda',
        grupoMuscular: 'Core',
        equipamiento: 'Bandas de resistencia',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Estabilidad',
        instrucciones: 'Con banda a la altura del pecho, empuja hacia adelante resistiendo la rotación',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Equilibrio a una pierna',
        slug: 'single-leg-balance',
        descripcion: 'Equilibrio en una pierna',
        grupoMuscular: 'Piernas',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Estabilidad',
        instrucciones: 'Mantén el equilibrio en una pierna, la otra flexionada',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Sentadillas en bosu',
        slug: 'bosu-ball-squats',
        descripcion: 'Sentadillas en bosu para estabilidad',
        grupoMuscular: 'Piernas',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Estabilidad',
        instrucciones: 'Realiza sentadillas sobre bosu ball manteniendo el equilibrio',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Levantamiento turco',
        slug: 'turkish-get-up',
        descripcion: 'Movimiento complejo de estabilidad',
        grupoMuscular: 'Core',
        equipamiento: 'Kettlebell',
        nivelDificultad: 'Avanzado',
        tipoEjercicio: 'Estabilidad',
        instrucciones: 'Desde acostado, levántate manteniendo el peso arriba con control total',
        arquetipo: true,
        publico: true,
        activo: true
      },
      // === EJERCICIOS DE HIIT ===
      {
        nombre: 'Sprints Tabata',
        slug: 'sprints-tabata',
        descripcion: 'Sprints de alta intensidad en intervalos',
        grupoMuscular: 'Piernas',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Avanzado',
        tipoEjercicio: 'HIIT',
        instrucciones: '20 segundos sprint máximo, 10 segundos descanso, repetir 8 rondas',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Cuerdas de batalla',
        slug: 'cuerdas-batalla',
        descripcion: 'Ondas con cuerdas pesadas de alta intensidad',
        grupoMuscular: 'Brazos',
        equipamiento: 'Cable',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'HIIT',
        instrucciones: 'Crea ondas alternas con las cuerdas a máxima velocidad',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Saltos a caja',
        slug: 'saltos-caja',
        descripcion: 'Saltos explosivos a caja',
        grupoMuscular: 'Piernas',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'HIIT',
        instrucciones: 'Salta explosivamente sobre una caja y baja controladamente',
        arquetipo: true,
        publico: true,
        activo: true
      },
      // === EJERCICIOS DE RESISTENCIA ===
      {
        nombre: 'Carrera',
        slug: 'carrera',
        descripcion: 'Carrera de resistencia cardiovascular',
        grupoMuscular: 'Piernas',
        equipamiento: 'Ninguno',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Resistencia',
        instrucciones: 'Mantén un ritmo constante de carrera durante el tiempo establecido',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Ciclismo',
        slug: 'ciclismo',
        descripcion: 'Ciclismo de resistencia',
        grupoMuscular: 'Piernas',
        equipamiento: 'Máquina',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Resistencia',
        instrucciones: 'Mantén un ritmo constante en bicicleta estática',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Remo',
        slug: 'remo',
        descripcion: 'Remo de resistencia en máquina',
        grupoMuscular: 'Espalda',
        equipamiento: 'Máquina',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Resistencia',
        instrucciones: 'Mantén un ritmo constante en máquina de remo',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Natación',
        slug: 'natacion',
        descripcion: 'Natación de resistencia',
        grupoMuscular: 'Piernas',
        equipamiento: 'Ninguno',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Resistencia',
        instrucciones: 'Mantén un ritmo constante de nado durante el tiempo establecido',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Elíptica',
        slug: 'eliptica',
        descripcion: 'Elíptica de resistencia',
        grupoMuscular: 'Piernas',
        equipamiento: 'Máquina',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Resistencia',
        instrucciones: 'Mantén un ritmo constante en elíptica',
        arquetipo: true,
        publico: true,
        activo: true
      },
      // === EJERCICIOS DE POTENCIA ===
      {
        nombre: 'Cargada y press',
        slug: 'cargada-press',
        descripcion: 'Movimiento explosivo de potencia',
        grupoMuscular: 'Piernas',
        equipamiento: 'Barra',
        nivelDificultad: 'Avanzado',
        tipoEjercicio: 'Potencia',
        instrucciones: 'Levanta la barra desde el suelo hasta los hombros y luego presiona por encima de la cabeza',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Arrancada',
        slug: 'arrancada',
        descripcion: 'Arrancada olímpica de potencia',
        grupoMuscular: 'Piernas',
        equipamiento: 'Barra',
        nivelDificultad: 'Avanzado',
        tipoEjercicio: 'Potencia',
        instrucciones: 'Levanta la barra desde el suelo hasta por encima de la cabeza en un movimiento',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Cargada de potencia',
        slug: 'cargada-potencia',
        descripcion: 'Cargada de potencia',
        grupoMuscular: 'Piernas',
        equipamiento: 'Barra',
        nivelDificultad: 'Avanzado',
        tipoEjercicio: 'Potencia',
        instrucciones: 'Levanta la barra desde el suelo hasta los hombros con movimiento explosivo',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Sentadillas con salto y peso',
        slug: 'sentadillas-salto-peso',
        descripcion: 'Sentadillas con salto y peso',
        grupoMuscular: 'Piernas',
        equipamiento: 'Mancuernas',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Potencia',
        instrucciones: 'Realiza sentadilla con peso y salta explosivamente',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Golpes con pelota medicinal',
        slug: 'golpes-pelota-medicinal',
        descripcion: 'Golpes explosivos con pelota medicinal',
        grupoMuscular: 'Core',
        equipamiento: 'Pelota medicinal',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Potencia',
        instrucciones: 'Levanta la pelota por encima de la cabeza y golpea el suelo con fuerza',
        arquetipo: true,
        publico: true,
        activo: true
      },
      // === MÁS EJERCICIOS DE CARDIO ===
      {
        nombre: 'Salto con cuerda',
        slug: 'salto-cuerda',
        descripcion: 'Salto con cuerda para cardio',
        grupoMuscular: 'Piernas',
        equipamiento: 'Cuerda para saltar',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Cardio',
        instrucciones: 'Salta con la cuerda manteniendo un ritmo constante',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Subidas de escalón',
        slug: 'subidas-escalon',
        descripcion: 'Subida de escalón para cardio',
        grupoMuscular: 'Piernas',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Cardio',
        instrucciones: 'Sube y baja de un escalón alternando las piernas',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Patadas al glúteo',
        slug: 'patadas-gluteo',
        descripcion: 'Patadas al glúteo corriendo',
        grupoMuscular: 'Piernas',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Cardio',
        instrucciones: 'Corre en el sitio llevando los talones hacia los glúteos',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Desplazamientos laterales',
        slug: 'desplazamientos-laterales',
        descripcion: 'Desplazamientos laterales',
        grupoMuscular: 'Piernas',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Cardio',
        instrucciones: 'Desplázate lateralmente manteniendo las rodillas flexionadas',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Caminata de cangrejo',
        slug: 'caminata-cangrejo',
        descripcion: 'Caminata de cangrejo',
        grupoMuscular: 'Piernas',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Cardio',
        instrucciones: 'Camina en posición de cangrejo hacia adelante y atrás',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Gateo de oso',
        slug: 'gateo-oso',
        descripcion: 'Gateo de oso para cardio',
        grupoMuscular: 'Piernas',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Cardio',
        instrucciones: 'Gatea manteniendo las rodillas ligeramente elevadas',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Saltos de patinador',
        slug: 'saltos-patinador',
        descripcion: 'Saltos de patinador',
        grupoMuscular: 'Piernas',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Cardio',
        instrucciones: 'Salta lateralmente de un lado a otro como un patinador',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Saltos de tijera cruzados',
        slug: 'saltos-tijera-cruzados',
        descripcion: 'Jumping jacks cruzados',
        grupoMuscular: 'Piernas',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Cardio',
        instrucciones: 'Salta cruzando brazos y piernas alternativamente',
        arquetipo: true,
        publico: true,
        activo: true
      },
      // === MÁS EJERCICIOS DE HIIT ===
      {
        nombre: 'Intervalos de sprint',
        slug: 'sprint-intervals',
        descripcion: 'Intervalos de sprint de alta intensidad',
        grupoMuscular: 'Piernas',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Avanzado',
        tipoEjercicio: 'HIIT',
        instrucciones: '30 segundos sprint máximo, 30 segundos descanso activo',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Variaciones de burpees',
        slug: 'burpee-variations',
        descripcion: 'Variaciones de burpees para HIIT',
        grupoMuscular: 'Piernas',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Avanzado',
        tipoEjercicio: 'HIIT',
        instrucciones: 'Burpees con salto, flexión, sentadilla y salto vertical',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Intervalos de escaladores',
        slug: 'mountain-climber-intervals',
        descripcion: 'Mountain climbers en intervalos de alta intensidad',
        grupoMuscular: 'Core',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'HIIT',
        instrucciones: '40 segundos máximo esfuerzo, 20 segundos descanso',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Intervalos de sentadillas con salto',
        slug: 'jump-squat-intervals',
        descripcion: 'Sentadillas con salto en intervalos',
        grupoMuscular: 'Piernas',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'HIIT',
        instrucciones: '45 segundos máximo esfuerzo, 15 segundos descanso',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Saltos en plancha',
        slug: 'plank-jacks',
        descripcion: 'Jumping jacks en posición de plancha',
        grupoMuscular: 'Core',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'HIIT',
        instrucciones: 'En plancha, abre y cierra las piernas como jumping jacks',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Escaladores araña',
        slug: 'spider-climbers',
        descripcion: 'Mountain climbers llevando rodilla al codo',
        grupoMuscular: 'Core',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Avanzado',
        tipoEjercicio: 'HIIT',
        instrucciones: 'Lleva la rodilla al codo opuesto alternativamente',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Saltos en pica',
        slug: 'pike-jumps',
        descripcion: 'Saltos en pica para HIIT',
        grupoMuscular: 'Core',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Avanzado',
        tipoEjercicio: 'HIIT',
        instrucciones: 'Salta llevando las piernas hacia arriba en posición de pica',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Saltos en estrella',
        slug: 'star-jumps',
        descripcion: 'Saltos en estrella de alta intensidad',
        grupoMuscular: 'Piernas',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'HIIT',
        instrucciones: 'Salta abriendo brazos y piernas en forma de estrella',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Saltos con rodillas al pecho',
        slug: 'tuck-jumps',
        descripcion: 'Saltos llevando rodillas al pecho',
        grupoMuscular: 'Piernas',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Avanzado',
        tipoEjercicio: 'HIIT',
        instrucciones: 'Salta llevando las rodillas al pecho en el aire',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Saltos laterales',
        slug: 'lateral-bounds',
        descripcion: 'Saltos laterales explosivos',
        grupoMuscular: 'Piernas',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Avanzado',
        tipoEjercicio: 'HIIT',
        instrucciones: 'Salta lateralmente de un lado a otro con máxima explosividad',
        arquetipo: true,
        publico: true,
        activo: true
      },
      // === MÁS EJERCICIOS DE RESISTENCIA ===
      {
        nombre: 'Ciclismo de larga distancia',
        slug: 'long-distance-cycling',
        descripcion: 'Ciclismo de larga distancia',
        grupoMuscular: 'Piernas',
        equipamiento: 'Máquina',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Resistencia',
        instrucciones: 'Mantén un ritmo constante durante 30+ minutos',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Esquí de fondo',
        slug: 'cross-country-skiing',
        descripcion: 'Esquí de fondo simulado',
        grupoMuscular: 'Piernas',
        equipamiento: 'Máquina',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Resistencia',
        instrucciones: 'Simula el movimiento de esquí de fondo en máquina',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Subida de escaleras',
        slug: 'stair-climbing',
        descripcion: 'Subida de escaleras de resistencia',
        grupoMuscular: 'Piernas',
        equipamiento: 'Máquina',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Resistencia',
        instrucciones: 'Sube escaleras manteniendo un ritmo constante',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Intervalos en máquina de remo',
        slug: 'rowing-machine-intervals',
        descripcion: 'Intervalos en máquina de remo',
        grupoMuscular: 'Espalda',
        equipamiento: 'Máquina',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Resistencia',
        instrucciones: 'Alterna períodos de alta y baja intensidad en remo',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Entrenamiento cruzado',
        slug: 'cross-training',
        descripcion: 'Entrenamiento cruzado de resistencia',
        grupoMuscular: 'Piernas',
        equipamiento: 'Máquina',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Resistencia',
        instrucciones: 'Combina diferentes máquinas cardiovasculares',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Senderismo',
        slug: 'hiking',
        descripcion: 'Senderismo de resistencia',
        grupoMuscular: 'Piernas',
        equipamiento: 'Ninguno',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Resistencia',
        instrucciones: 'Caminata en terreno variado durante tiempo prolongado',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Caminata nórdica',
        slug: 'nordic-walking',
        descripcion: 'Caminata nórdica con bastones',
        grupoMuscular: 'Piernas',
        equipamiento: 'Ninguno',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Resistencia',
        instrucciones: 'Caminata con bastones manteniendo ritmo constante',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Aeróbicos acuáticos',
        slug: 'water-aerobics',
        descripcion: 'Aeróbicos acuáticos de resistencia',
        grupoMuscular: 'Piernas',
        equipamiento: 'Ninguno',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Resistencia',
        instrucciones: 'Ejercicios aeróbicos en agua durante tiempo prolongado',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Cardio con baile',
        slug: 'dance-cardio',
        descripcion: 'Baile cardiovascular de resistencia',
        grupoMuscular: 'Piernas',
        equipamiento: 'Ninguno',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Resistencia',
        instrucciones: 'Baila manteniendo un ritmo constante durante tiempo prolongado',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Entrenamiento en circuito',
        slug: 'circuit-training',
        descripcion: 'Entrenamiento en circuito de resistencia',
        grupoMuscular: 'Piernas',
        equipamiento: 'Máquina',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Resistencia',
        instrucciones: 'Rota entre diferentes máquinas sin descanso prolongado',
        arquetipo: true,
        publico: true,
        activo: true
      },
      // === MÁS EJERCICIOS DE POTENCIA ===
      {
        nombre: 'Cargada desde colgado',
        slug: 'hang-clean',
        descripcion: 'Cargada desde colgado',
        grupoMuscular: 'Piernas',
        equipamiento: 'Barra',
        nivelDificultad: 'Avanzado',
        tipoEjercicio: 'Potencia',
        instrucciones: 'Carga la barra desde posición colgada hasta los hombros',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Press con impulso',
        slug: 'push-press',
        descripcion: 'Press con impulso de piernas',
        grupoMuscular: 'Hombros',
        equipamiento: 'Barra',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Potencia',
        instrucciones: 'Usa el impulso de las piernas para presionar la barra por encima',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Empuje',
        slug: 'thruster',
        descripcion: 'Sentadilla con press por encima',
        grupoMuscular: 'Piernas',
        equipamiento: 'Barra',
        nivelDificultad: 'Avanzado',
        tipoEjercicio: 'Potencia',
        instrucciones: 'Sentadilla seguida inmediatamente de press por encima',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Cargada con kettlebell',
        slug: 'kettlebell-clean',
        descripcion: 'Cargada con kettlebell',
        grupoMuscular: 'Piernas',
        equipamiento: 'Kettlebell',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Potencia',
        instrucciones: 'Carga la kettlebell desde el suelo hasta la posición de rack',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Arrancada con kettlebell',
        slug: 'kettlebell-snatch',
        descripcion: 'Arrancada con kettlebell',
        grupoMuscular: 'Piernas',
        equipamiento: 'Kettlebell',
        nivelDificultad: 'Avanzado',
        tipoEjercicio: 'Potencia',
        instrucciones: 'Arranca la kettlebell desde el suelo hasta por encima en un movimiento',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Cargada de potencia con mancuernas',
        slug: 'dumbbell-power-clean',
        descripcion: 'Cargada de potencia con mancuernas',
        grupoMuscular: 'Piernas',
        equipamiento: 'Mancuernas',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Potencia',
        instrucciones: 'Carga las mancuernas desde el suelo hasta los hombros',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Zancadas con salto',
        slug: 'jump-lunges',
        descripcion: 'Zancadas con salto explosivo',
        grupoMuscular: 'Piernas',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Potencia',
        instrucciones: 'Alterna zancadas con salto explosivo entre cada repetición',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Saltos horizontales',
        slug: 'broad-jumps',
        descripcion: 'Saltos horizontales de potencia',
        grupoMuscular: 'Piernas',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Potencia',
        instrucciones: 'Salta horizontalmente lo más lejos posible',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Balanceo con kettlebell a un brazo',
        slug: 'single-arm-kettlebell-swing',
        descripcion: 'Balanceo con kettlebell a un brazo',
        grupoMuscular: 'Piernas',
        equipamiento: 'Kettlebell',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Potencia',
        instrucciones: 'Balancea la kettlebell con un solo brazo hasta la altura del pecho',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Lanzamientos de pelota a la pared',
        slug: 'wall-ball-shots',
        descripcion: 'Lanzamientos de pelota a la pared',
        grupoMuscular: 'Piernas',
        equipamiento: 'Pelota medicinal',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Potencia',
        instrucciones: 'Lanza la pelota a la pared desde sentadilla con máxima potencia',
        arquetipo: true,
        publico: true,
        activo: true
      },
      // === MÁS EJERCICIOS DE FLEXIBILIDAD ===
      {
        nombre: 'Estiramiento gato-vaca',
        slug: 'estiramiento-gato-vaca',
        descripcion: 'Estiramiento de gato-vaca para columna',
        grupoMuscular: 'Espalda',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Flexibilidad',
        instrucciones: 'En cuadrupedia, alterna entre arquear y redondear la espalda',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Perro boca abajo',
        slug: 'perro-boca-abajo',
        descripcion: 'Postura del perro boca abajo',
        grupoMuscular: 'Espalda',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Flexibilidad',
        instrucciones: 'Forma una V invertida con el cuerpo, estirando toda la cadena posterior',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Postura del niño',
        slug: 'postura-del-nino',
        descripcion: 'Postura del niño para relajación',
        grupoMuscular: 'Espalda',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Flexibilidad',
        instrucciones: 'Siéntate sobre los talones y estira los brazos hacia adelante',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Postura de la paloma',
        slug: 'postura-de-la-paloma',
        descripcion: 'Postura de la paloma para flexibilidad de cadera',
        grupoMuscular: 'Piernas',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Flexibilidad',
        instrucciones: 'Lleva una pierna hacia adelante en ángulo, estira la otra hacia atrás',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Flexión sentada hacia adelante',
        slug: 'flexion-sentada-hacia-adelante',
        descripcion: 'Flexión hacia adelante sentado',
        grupoMuscular: 'Espalda',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Flexibilidad',
        instrucciones: 'Sentado con piernas extendidas, flexiona hacia adelante desde la cadera',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Flexión de pie hacia adelante',
        slug: 'flexion-pie-hacia-adelante',
        descripcion: 'Flexión hacia adelante de pie',
        grupoMuscular: 'Espalda',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Flexibilidad',
        instrucciones: 'De pie, flexiona hacia adelante desde la cadera, colgando los brazos',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Guerrero III',
        slug: 'guerrero-iii',
        descripcion: 'Guerrero III para equilibrio y flexibilidad',
        grupoMuscular: 'Piernas',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Flexibilidad',
        instrucciones: 'Equilibrio en una pierna, cuerpo y pierna libre paralelos al suelo',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Postura del triángulo',
        slug: 'postura-del-triangulo',
        descripcion: 'Postura del triángulo para flexibilidad lateral',
        grupoMuscular: 'Espalda',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Flexibilidad',
        instrucciones: 'Piernas separadas, inclínate hacia un lado tocando el tobillo',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Postura de la cobra',
        slug: 'postura-de-la-cobra',
        descripcion: 'Postura de la cobra para flexibilidad de columna',
        grupoMuscular: 'Espalda',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Flexibilidad',
        instrucciones: 'Acostado boca abajo, levanta el pecho apoyándote en los antebrazos',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Postura del puente',
        slug: 'postura-del-puente',
        descripcion: 'Postura del puente para flexibilidad de columna',
        grupoMuscular: 'Espalda',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Flexibilidad',
        instrucciones: 'Acostado boca arriba, levanta las caderas formando un puente',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Estiramiento de mariposa',
        slug: 'estiramiento-de-mariposa',
        descripcion: 'Estiramiento de mariposa para cadera',
        grupoMuscular: 'Piernas',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Flexibilidad',
        instrucciones: 'Sentado, une las plantas de los pies y acerca los talones al cuerpo',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Torsión sentada de columna',
        slug: 'torsion-sentada-columna',
        descripcion: 'Torsión sentada de columna',
        grupoMuscular: 'Espalda',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Flexibilidad',
        instrucciones: 'Sentado, gira el torso hacia un lado, mano opuesta en la rodilla',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Postura del lagarto',
        slug: 'postura-del-lagarto',
        descripcion: 'Postura del lagarto para flexibilidad de cadera',
        grupoMuscular: 'Piernas',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Flexibilidad',
        instrucciones: 'En posición de zancada baja, apoya los antebrazos en el suelo',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Estiramiento de isquiotibiales acostado',
        slug: 'estiramiento-isquiotibiales-acostado',
        descripcion: 'Estiramiento de isquiotibiales acostado',
        grupoMuscular: 'Piernas',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Flexibilidad',
        instrucciones: 'Acostado, lleva una rodilla al pecho y extiende la pierna hacia arriba',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Postura del águila',
        slug: 'postura-del-aguila',
        descripcion: 'Postura del águila para flexibilidad de hombros',
        grupoMuscular: 'Hombros',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Intermedio',
        tipoEjercicio: 'Flexibilidad',
        instrucciones: 'Envuelve un brazo alrededor del otro y cruza las piernas',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Enhebrar la aguja',
        slug: 'enhebrar-la-aguja',
        descripcion: 'Enhebrar la aguja para flexibilidad de hombros',
        grupoMuscular: 'Hombros',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Flexibilidad',
        instrucciones: 'En cuadrupedia, pasa un brazo por debajo del otro',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Postura del bebé feliz',
        slug: 'postura-del-bebe-feliz',
        descripcion: 'Postura del bebé feliz para flexibilidad de cadera',
        grupoMuscular: 'Piernas',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Flexibilidad',
        instrucciones: 'Acostado boca arriba, agarra los pies y balancea suavemente',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Piernas en la pared',
        slug: 'piernas-en-la-pared',
        descripcion: 'Piernas en la pared para relajación',
        grupoMuscular: 'Piernas',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Flexibilidad',
        instrucciones: 'Acostado cerca de la pared, eleva las piernas contra la pared',
        arquetipo: true,
        publico: true,
        activo: true
      },
      {
        nombre: 'Ángulo atado reclinado',
        slug: 'angulo-atado-reclinado',
        descripcion: 'Ángulo atado reclinado para flexibilidad de cadera',
        grupoMuscular: 'Piernas',
        equipamiento: 'Peso corporal',
        nivelDificultad: 'Principiante',
        tipoEjercicio: 'Flexibilidad',
        instrucciones: 'Acostado, une las plantas de los pies y deja caer las rodillas',
        arquetipo: true,
        publico: true,
        activo: true
      }
    ];

    // Crear ejercicios
    const ejerciciosCreados = await Ejercicio.insertMany(ejercicios);
    console.log(`${ejerciciosCreados.length} ejercicios creados exitosamente.`);

    return ejerciciosCreados;
  } catch (error) {
    console.error('Error en seed de ejercicios:', error);
    throw error;
  }
}